name: Lint Commit Messages

on: [ pull_request ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6.0.8

      - name: Setup node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - run: pnpm install
      - uses: wagoid/commitlint-github-action@v6.2.0
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
